#we use java
language: java

#we add the java development kit (jdk)
jdk:
  - openjdk11

services:
  #Linking Travis CI and Docker
  - docker
# SonarCloud
addons:
  sonarcloud:
    organization: spring-boot-cicd
    token:
      # encrypted value of your token
      secure: mEdWbanq87zkmbg/NTuaof/8zCSwpsvfEpAOP9M1Z/NRmj6DQ6Roq8XodImD5XSgJQARaacAylJc5clp39N3xqv3VRtLv25RpCkDqAdOVACH8o+YvQsWHiDbpnbvXSOBLrzUlVQ9ZA8U+j5nVbnGLH99G/TfUCk0E7nQtXMxmmkmLYsTp7j9x+zAsV/zwrqqz6iTKgd3E8oiRREV5jfZdnjHBR/1ecLMoQCaZljJISKGaNoZ090va0IwG6IQHTSb8Hhh2L9/DOayu/I6Tp2sHHUioIY+rkp+kq5icaiuM/WSPci6t0sEaQ6jps4vD6+yGDVdk48t1yU7goX68DkJGF34/LwGWnNlnPl8S867YLBkpeOrEopyPd9oMpECuN/n9ZwfZ/J7amXUaTAV0/kUkF110NkNx2WtWC/1BB+kIxOHb4W6zpwlUhQZmJrX/6llCZ4dU0Q5P91+QmMQbZCIchDEINc+mkgobVsST4MtKx8/9ZnViYInfXqlV4+SlB1nFbkYoMIeUKL7EgR67Su+HTmUfx9D0b56P3j1MH8dpnjUUV+Igv7eoIxcG1e0dDgnJEnMrstTfsr1xvuNeMofl/aZW+wyWOFHnKNWEEcp0oBz8nYU/TEeF5+hc5o73DHC2cqk7DIGPvorQFcwP8d2lkXXWiA5vxlziDomrMLtnAQ=

before_install:
  - mvn clean
  - echo "$DOCKER_PASSWORD" | docker login  -u "$DOCKER_USERNAME" --password-stdin
  - docker pull adoptopenjdk/openjdk11:ubi

script:
  #We avoid this error :" the job exceeded the maximum log length and has been terminated "
  - echo -e '<?xml version="1.0" encoding="UTF-8"?>\n<settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd" xmlns="http://maven.apache.org/SETTINGS/1.1.0"\n    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n  <mirrors>\n    <mirror>\n      <id>mvnsearch-unavailable</id>\n      <name>mvnsearch-unavailable</name>\n      <mirrorOf>mvnsearch</mirrorOf>\n      <url>http://repo1.maven.org/maven2</url>\n    </mirror>\n  </mirrors>\n  <profiles>\n    <profile>\n      <id>no-mvnsearch</id>\n      <repositories>\n        <repository>\n          <id>mvnsearch</id>\n          <url>http://www.mvnsearch.org/maven2</url>\n          <releases>\n            <enabled>true</enabled>\n          </releases>\n          <snapshots>\n            <enabled>true</enabled>\n          </snapshots>\n        </repository>\n      </repositories>\n    </profile>\n  </profiles>\n  <activeProfiles>\n    <activeProfile>no-mvnsearch</activeProfile>\n  </activeProfiles>\n</settings>' > $HOME/.m2/settings.xml
  - cat $HOME/.m2/settings.xml
  #deploying the app on Docker & Heroku
  - mvn heroku:deploy
after_success:
  #Generating Site
  - travis_wait mvn site
  - bash <(curl -s https://codecov.io/bash)
  # SonarCloud
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
